name: Check Cargo Version

on:
    pull_request:
        branches:
            - release/*

jobs:
    check-cargo-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Git
              run: |
                git fetch --tags

            - name: Get latest tag from main branch
              id: get_latest_tag
              run: |
                LATEST_TAG=$(git fetch origin main --tags && git tag --sort=-creatordate | head -n 1 | sed 's/^v//')
                echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

            - name: Get Cargo.toml version
              id: get_cargo_version
              run: |
                CARGO_VERSION=$(awk '/^version = "/ {gsub(/"/, "", $3); print $3; exit}' Cargo.toml)
                echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

            - name: Compare versions
              id: compare_versions
              run: |
                if [ "$CARGO_VERSION" = "$LATEST_TAG" ]; then
                echo "Error: Cargo.toml version ($CARGO_VERSION) has not been updated since the last tag ($LATEST_TAG)."
                exit 1
                else
                echo "Cargo.toml version ($CARGO_VERSION) has been updated since the last tag ($LATEST_TAG)."
                fi