name: "CI Nix"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
      - bugfix/*
      
  pull_request:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Run nix flake check
        run: NIX_SKIP_TEMPLATE=1 nix flake check --show-trace --impure --print-build-logs
        
